# Generated by Django 2.0.6 on 2019-07-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 't_person',
            },
        ),
    ]
