# Generated by Django 2.0.6 on 2019-07-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=20)),
                ('hometown', models.CharField(max_length=20)),
                ('living_place', models.CharField(max_length=20)),
                ('ideal_position', models.CharField(max_length=40)),
                ('ideal_city', models.CharField(max_length=60)),
                ('salary', models.CharField(max_length=60)),
                ('standby1', models.CharField(max_length=20, null=True)),
                ('standby2', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
